language: java

jdk: openjdk8

branches:
  only:
    - master

before_install:
  - echo $GITHUB_TOKEN


install: mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

## Build and release to maven central
script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U

## Get the project version
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')


cache:
  directories:
    - "~/.m2/repository"


after_success:
  - mvn clean test jacoco:report coveralls:report

